apiVersion: v2
name: patchwork
description: Watches deployments, daemonsets, and statefulsets for image updates and will automatically trigger rollouts to pull in updates
type: application
version: 0.8.0
appVersion: '0.4.0'
dependencies:
  - name: redis
    repository: https://groundhog2k.github.io/helm-charts/
    version: 0.6.12
  - name: psa-restricted-patcher
    repository: https://bryopsida.github.io/psa-restricted-patcher/
    version: 0.10.0
    condition: psaPatcher.enabled
    alias: psaPatcher
maintainers:
  - name: bryopsida
