apiVersion: v2
name: patchwork
description: Watches deployments, daemonsets, and statefulsets for image updates and will automatically trigger rollouts to pull in updates
type: application
version: 0.8.2
appVersion: '0.4.0'
dependencies:
  - name: redis
    repository: https://groundhog2k.github.io/helm-charts/
    version: 0.6.13
  - name: psa-restricted-patcher
    repository: https://bryopsida.github.io/psa-restricted-patcher/
    version: 0.10.1
    condition: psa-patcher.enabled
    alias: psa-patcher
maintainers:
  - name: bryopsida
