apiVersion: v2
name: patchwork
description: A Helm chart for Kubernetes
type: application
version: 0.4.0
appVersion: '0.4.0'
dependencies:
  - name: redis
    repository: https://groundhog2k.github.io/helm-charts/
    version: 0.6.12
maintainers:
  - name: bryopsida
